<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_jobs_delete' => [['name'], ['_controller' => 'App\\Controller\\JobsController::delete'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/jobs/delete']], [], [], []],
    'app_jobs_index' => [[], ['_controller' => 'App\\Controller\\JobsController::post'], [], [['text', '/jobs']], [], [], []],
    'app_jobs_view' => [[], ['_controller' => 'App\\Controller\\JobsController::read'], [], [['text', '/jobs']], [], [], []],
    'App\Controller\JobsController::post' => [[], ['_controller' => 'App\\Controller\\JobsController::post'], [], [['text', '/jobs']], [], [], []],
    'App\Controller\JobsController::delete' => [['name'], ['_controller' => 'App\\Controller\\JobsController::delete'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/jobs/delete']], [], [], []],
    'App\Controller\JobsController::read' => [[], ['_controller' => 'App\\Controller\\JobsController::read'], [], [['text', '/jobs']], [], [], []],
];
